import { useState } from "react";

import { BillingProfileReactQueryAdapter } from "@/core/application/react-query-adapter/billing-profile";
import { UploadBillingProfileInvoiceByIdPortParams } from "@/core/domain/billing-profile/billing-profile-contract.types";

import { toast } from "@/design-system/molecules/toaster";

import { UseInvoiceUploadProps } from "@/shared/features/invoice/hooks/use-invoice-upload/use-invoice-upload.types";
import { useSidePanelsContext } from "@/shared/features/side-panels/side-panels.context";
import { usePosthog } from "@/shared/tracking/posthog/use-posthog";
import { Translate } from "@/shared/translation/components/translate/translate";

export function useInvoiceUpload({ billingProfileId, invoiceId }: UseInvoiceUploadProps) {
  const { capture } = usePosthog();
  const { close } = useSidePanelsContext();

  const [queryParams, setQueryParams] = useState<UploadBillingProfileInvoiceByIdPortParams["queryParams"]>();

  const { mutate: uploadInvoice, isPending: isPendingUploadInvoice } =
    BillingProfileReactQueryAdapter.client.useUploadBillingProfileInvoiceById({
      pathParams: {
        billingProfileId,
        invoiceId,
      },
      queryParams,
      options: {
        onSuccess: () => {
          toast.success(<Translate token={"features:invoices.invoiceSubmission.toaster.success"} />);
          close();
        },
        onError: () => {
          toast.error(<Translate token={"features:invoices.invoiceSubmission.toaster.error"} />);
        },
      },
    });

  function handleSetFileName(fileName: string) {
    setQueryParams({ fileName });
  }

  function handleSendManualInvoice(fileBlob: Blob) {
    if (fileBlob) {
      uploadInvoice(fileBlob);
      capture("invoice_submitted", { type: "manual" });
    } else {
      toast.error(<Translate token="features:invoices.invoiceSubmission.toaster.emptyFile" />);
    }
  }

  function handleSendAutoGeneratedInvoice(fileBlob: Blob) {
    if (fileBlob) {
      uploadInvoice(fileBlob);
      capture("invoice_submitted", { type: "auto-generated" });
    } else {
      toast.error(<Translate token="features:invoices.invoiceSubmission.toaster.emptyFile" />);
    }
  }

  return { isPendingUploadInvoice, handleSetFileName, handleSendManualInvoice, handleSendAutoGeneratedInvoice };
}
