export const MARKETPLACE_API_BASE_URL = `https://${process.env.NEXT_PUBLIC_ONLYDUST_API_BASEPATH}`;
export const MARKETPLACE_API_MOCK_URL = `http://${process.env.NEXT_PUBLIC_ONLYDUST_API_MOCK_BASEPATH}`;
