import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";

import "@/app/globals.css";
import { Providers } from "@/app/providers";

import { CommonTranslate } from "@/shared/i18n/common.translate";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <CommonTranslate>{children}</CommonTranslate>
        </Providers>
      </body>
    </html>
  );
}
