export enum ProjectTag {
  HOT_COMMUNITY = "HOT_COMMUNITY",
  NEWBIES_WELCOME = "NEWBIES_WELCOME",
  LIKELY_TO_REWARD = "LIKELY_TO_REWARD",
  WORK_IN_PROGRESS = "WORK_IN_PROGRESS",
  FAST_AND_FURIOUS = "FAST_AND_FURIOUS",
  BIG_WHALE = "BIG_WHALE",
  UPDATED_ROADMAP = "UPDATED_ROADMAP",
  HAS_GOOD_FIRST_ISSUES = "HAS_GOOD_FIRST_ISSUES",
}

export type ProjectTagUnion = `${ProjectTag}`;
