export const COLORS = {
  typography: {
    primary: "var(--typography-primary)",
    "primary-on-brand": "var(--typography-primary_on-brand)",
    secondary: "var(--typography-secondary)",
    "secondary-hover": "var(--typography-secondary_hover)",
    tertiary: "var(--typography-tertiary)",
    "tertiary-hover": "var(--typography-tertiary_hover)",
    quaternary: "var(--typography-quaternary)",
    white: "var(--typography-white)",
    disabled: "var(--typography-disabled)",
    placeholder: "var(--typography-placeholder)",
    error: "var(--typography-error)",
    "error-hover": "var(--typography-error_hover)",
    warning: "var(--typography-warning)",
    "brand-primary": "var(--typography-brand-primary)",
    "brand-secondary": "var(--typography-brand-secondary)",
    "brand-secondary-alt": "var(--typography-brand-secondary_alt)",
    "brand-secondary-alt-hover": "var(--typography-brand-secondary_alt_hover)",
    "brand-tertiary": "var(--typography-brand-tertiary)",
    success: "var(--typography-success)",
  },
  border: {
    primary: "var(--border-primary)",
    "primary-hover": "var(--border-primary_hover)",
    "primary-alt": "var(--border-primary_alt)",
    secondary: "var(--border-secondary)",
    tertiary: "var(--border-tertiary)",
    disabled: "var(--border-disabled)",
    "brand-primary": "var(--border-brand-primary)",
    "brand-secondary": "var(--border-brand-secondary)",
    "error-primary": "var(--border-error-primary)",
    "error-secondary": "var(--border-error-secondary)",
    "error-secondary-hover": "var(--border-error-secondary_hover)",
    "warning-primary": "var(--border-warning-primary)",
    "warning-secondary": "var(--border-warning-secondary)",
    "success-primary": "var(--border-success-primary)",
    active: "var(--border-active)",
    "success-secondary": "var(--border-success-secondary)",
  },
  chart: {
    primary: "var(--chart-primary)",
    secondary: "var(--chart-secondary)",
    tertiary: "var(--chart-tertiary)",
    quaternary: "var(--chart-quaternary)",
    quinary: "var(--chart-quinary)",
    senary: "var(--chart-senary)",
    septenary: "var(--chart-septenary)",
    octonary: "var(--chart-octonary)",
  },
  foreground: {
    primary: "var(--foreground-primary)",
    secondary: "var(--foreground-secondary)",
    "secondary-hover": "var(--foreground-secondary_hover)",
    tertiary: "var(--foreground-tertiary)",
    "tertiary-hover": "var(--foreground-tertiary_hover)",
    quaternary: "var(--foreground-quaternary)",
    "quaternary-hover": "var(--foreground-quaternary_hover)",
    quinary: "var(--foreground-quinary)",
    "quinary-hover": "var(--foreground-quinary_hover)",
    senary: "var(--foreground-senary)",
    white: "var(--foreground-white)",
    disabled: "var(--foreground-disabled)",
    "brand-primary": "var(--foreground-brand-primary)",
    "brand-secondary": "var(--foreground-brand-secondary)",
    "brand-secondary-hover": "var(--foreground-brand-secondary_hover)",
    error: "var(--foreground-error)",
    "error-hover": "var(--foreground-error_hover)",
    warning: "var(--foreground-warning)",
    success: "var(--foreground-success)",
  },
  background: {
    primary: "var(--background-primary)",
    "primary-hover": "var(--background-primary_hover)",
    "primary-alt": "var(--background-primary_alt)",
    "primary-alt-hover": "var(--background-primary_alt_hover)",
    "primary-solid": "var(--background-primary-solid)",
    secondary: "var(--background-secondary)",
    "secondary-hover": "var(--background-secondary_hover)",
    "secondary-alt": "var(--background-secondary_alt)",
    "secondary-alt-2": "var(--background-secondary_alt_2)",
    tertiary: "var(--background-tertiary)",
    "tertiary-hover": "var(--background-tertiary_hover)",
    quaternary: "var(--background-quaternary)",
    active: "var(--background-active)",
    disabled: "var(--background-disabled)",
    "disabled-alt": "var(--background-disabled_alt)",
    overlay: "var(--background-overlay)",
    error: "var(--background-error)",
    "error-alt": "var(--background-error_alt)",
    "error-solid": "var(--background-error-solid)",
    "error-solid-hover": "var(--background-error-solid_hover)",
    "brand-primary": "var(--background-brand-primary)",
    "brand-primary-alt": "var(--background-brand-primary_alt)",
    "brand-primary-solid": "var(--background-brand-primary-solid)",
    "brand-primary-solid-hover": "var(--background-brand-primary-solid_hover)",
    "brand-secondary": "var(--background-brand-secondary)",
    warning: "var(--background-warning)",
    "warning-alt": "var(--background-warning_alt)",
    "warning-solid": "var(--background-warning-solid)",
    "warning-solid-hover": "var(--background-warning-solid_hover)",
    success: "var(--background-success)",
    "success-alt": "var(--background-success_alt)",
    "success-solid": "var(--background-success-solid)",
    "success-solid-hover": "var(--background-success-solid_hover)",
  },
  effects: {
    "focusrings-brand-spaced": "var(--effects-focusrings-brand-spaced)",
    "focusrings-brand-glued": "var(--effects-focusrings-brand-glued)",
    "focusrings-error-spaced": "var(--effects-focusrings-error-spaced)",
    "focusrings-error-glued": "var(--effects-focusrings-error-glued)",
    "shadow-xs": "var(--effects-shadow-xs)",
    "shadow-sm-1": "var(--effects-shadow-sm_1)",
    "shadow-sm-2": "var(--effects-shadow-sm_2)",
    "shadow-md-1": "var(--effects-shadow-md_1)",
    "shadow-md-2": "var(--effects-shadow-md_2)",
    "shadow-lg-1": "var(--effects-shadow-lg_1)",
    "shadow-lg-2": "var(--effects-shadow-lg_2)",
    "shadow-xl-1": "var(--effects-shadow-xl_1)",
    "shadow-xl-2": "var(--effects-shadow-xl_2)",
  },
  utility: {
    "alpha-white": {
      0: "var(--utility-alpha-white-0)",
      5: "var(--utility-alpha-white-5)",
      10: "var(--utility-alpha-white-10)",
      20: "var(--utility-alpha-white-20)",
      30: "var(--utility-alpha-white-30)",
      40: "var(--utility-alpha-white-40)",
      50: "var(--utility-alpha-white-50)",
      60: "var(--utility-alpha-white-60)",
      70: "var(--utility-alpha-white-70)",
      80: "var(--utility-alpha-white-80)",
      90: "var(--utility-alpha-white-90)",
      100: "var(--utility-alpha-white-100)",
    },
    "alpha-black": {
      0: "var(--utility-alpha-black-0)",
      5: "var(--utility-alpha-black-5)",
      10: "var(--utility-alpha-black-10)",
      20: "var(--utility-alpha-black-20)",
      30: "var(--utility-alpha-black-30)",
      40: "var(--utility-alpha-black-40)",
      50: "var(--utility-alpha-black-50)",
      60: "var(--utility-alpha-black-60)",
      70: "var(--utility-alpha-black-70)",
      80: "var(--utility-alpha-black-80)",
      90: "var(--utility-alpha-black-90)",
      100: "var(--utility-alpha-black-100)",
    },
    grey: {
      50: "var(--utility-grey-50)",
      100: "var(--utility-grey-100)",
      200: "var(--utility-grey-200)",
      300: "var(--utility-grey-300)",
      400: "var(--utility-grey-400)",
      500: "var(--utility-grey-500-primary)",
      600: "var(--utility-grey-600)",
      700: "var(--utility-grey-700)",
      800: "var(--utility-grey-800)",
      900: "var(--utility-grey-900)",
    },
    "brand-brightorange": {
      50: "var(--utility-brand-brightorange-50)",
      100: "var(--utility-brand-brightorange-100)",
      200: "var(--utility-brand-brightorange-200)",
      300: "var(--utility-brand-brightorange-300)",
      400: "var(--utility-brand-brightorange-400)",
      500: "var(--utility-brand-brightorange-500-primary)",
      600: "var(--utility-brand-brightorange-600)",
      700: "var(--utility-brand-brightorange-700)",
      800: "var(--utility-brand-brightorange-800)",
      900: "var(--utility-brand-brightorange-900)",
    },
    "brand-crystalizedviolet": {
      50: "var(--utility-brand-crystalizedviolet-50)",
      100: "var(--utility-brand-crystalizedviolet-100)",
      200: "var(--utility-brand-crystalizedviolet-200)",
      300: "var(--utility-brand-crystalizedviolet-300)",
      400: "var(--utility-brand-crystalizedviolet-400)",
      500: "var(--utility-brand-crystalizedviolet-500-primary)",
      600: "var(--utility-brand-crystalizedviolet-600)",
      700: "var(--utility-brand-crystalizedviolet-700)",
      800: "var(--utility-brand-crystalizedviolet-800)",
      900: "var(--utility-brand-crystalizedviolet-900)",
    },
    "brand-electricroyalblue": {
      50: "var(--utility-brand-electricroyalblue-50)",
      100: "var(--utility-brand-electricroyalblue-100)",
      200: "var(--utility-brand-electricroyalblue-200)",
      300: "var(--utility-brand-electricroyalblue-300)",
      400: "var(--utility-brand-electricroyalblue-400)",
      500: "var(--utility-brand-electricroyalblue-500-primary)",
      600: "var(--utility-brand-electricroyalblue-600)",
      700: "var(--utility-brand-electricroyalblue-700)",
      800: "var(--utility-brand-electricroyalblue-800)",
      900: "var(--utility-brand-electricroyalblue-900)",
    },
    "brand-cyan": {
      50: "var(--utility-brand-cyan-50)",
      100: "var(--utility-brand-cyan-100)",
      200: "var(--utility-brand-cyan-200)",
      300: "var(--utility-brand-cyan-300)",
      400: "var(--utility-brand-cyan-400)",
      500: "var(--utility-brand-cyan-500-primary)",
      600: "var(--utility-brand-cyan-600)",
      700: "var(--utility-brand-cyan-700)",
      800: "var(--utility-brand-cyan-800)",
      900: "var(--utility-brand-cyan-900)",
    },
    secondary: {
      "blue-500": "var(--utility-secondary-blue-500)",
      "yellow-500": "var(--utility-secondary-yellow-500)",
      "orange-500": "var(--utility-secondary-orange-500)",
      "green-500": "var(--utility-secondary-green-500)",
      "pink-500": "var(--utility-secondary-pink-500)",
    },
    error: {
      50: "var(--utility-error-50)",
      100: "var(--utility-error-100)",
      200: "var(--utility-error-200)",
      300: "var(--utility-error-300)",
      400: "var(--utility-error-400)",
      500: "var(--utility-error-500-primary)",
      600: "var(--utility-error-600)",
      700: "var(--utility-error-700)",
      800: "var(--utility-error-800)",
      900: "var(--utility-error-900)",
    },
    warning: {
      50: "var(--utility-warning-50)",
      100: "var(--utility-warning-100)",
      200: "var(--utility-warning-200)",
      300: "var(--utility-warning-300)",
      400: "var(--utility-warning-400)",
      500: "var(--utility-warning-500-primary)",
      600: "var(--utility-warning-600)",
      700: "var(--utility-warning-700)",
      800: "var(--utility-warning-800)",
      900: "var(--utility-warning-900)",
    },
    success: {
      50: "var(--utility-success-50)",
      100: "var(--utility-success-100)",
      200: "var(--utility-success-200)",
      300: "var(--utility-success-300)",
      400: "var(--utility-success-400)",
      500: "var(--utility-success-500-primary)",
      600: "var(--utility-success-600)",
      700: "var(--utility-success-700)",
      800: "var(--utility-success-800)",
      900: "var(--utility-success-900)",
    },
  },
  components: {
    badge: {
      grey: {
        "closexitem-bg": "var(--components-badge-grey-closexitem-bg)",
        "closexitem-fg": "var(--components-badge-grey-closexitem-fg)",
        "closexitem-bg-hover": "var(--components-badge-grey-closexitem-bg_hover)",
        bg: "var(--components-badge-grey-bg)",
        fg: "var(--components-badge-grey-fg)",
        "fg-hover": "var(--components-badge-grey-closexitem-fg_hover)",
        typo: "var(--components-badge-grey-typo)",
        border: "var(--components-badge-grey-border)",
      },
      brand: {
        "closexitem-bg": "var(--components-badge-brand-closexitem-bg)",
        bg: "var(--components-badge-brand-bg)",
        fg: "var(--components-badge-brand-fg)",
        "closexitem-bg-hover": "var(--components-badge-brand-closexitem-bg_hover)",
        typo: "var(--components-badge-brand-typo)",
        border: "var(--components-badge-brand-border)",
        "closexitem-fg": "var(--components-badge-brand-closexitem-fg)",
        "closexitem-fg-hover": "var(--components-badge-brand-closexitem-fg_hover)",
      },
      error: {
        "closexitem-bg": "var(--components-badge-error-closexitem-bg)",
        bg: "var(--components-badge-error-bg)",
        "closexitem-bg-hover": "var(--components-badge-error-closexitem-bg_hover)",
        fg: "var(--components-badge-error-fg)",
        typo: "var(--components-badge-error-typo)",
        border: "var(--components-badge-error-border)",
        "closexitem-fg": "var(--components-badge-error-closexitem-fg)",
        "closexitem-fg-hover": "var(--components-badge-error-closexitem-fg_hover)",
      },
      "badge-warning": {
        bg: "var(--components-badge-warning-bg)",
        "closexitem-bg-hover": "var(--components-badge-warning-closexitem-bg_hover)",
        border: "var(--components-badge-warning-border)",
        "closexitem-fg": "var(--components-badge-warning-closexitem-fg)",
        "closexitem-fg-hover": "var(--components-badge-warning-closexitem-fg_hover)",
        fg: "var(--components-badge-warning-fg)",
        typo: "var(--components-badge-warning-typo)",
        "closexitem-bg": "var(--components-badge-warning-closexitem-bg)",
      },
      success: {
        "closexitem-bg": "var(--components-badge-success-closexitem-bg)",
        bg: "var(--components-badge-success-bg)",
        "closexitem-bg-hover": "var(--components-badge-success-closexitem-bg_hover)",
        fg: "var(--components-badge-success-fg)",
        typo: "var(--components-badge-success-typo)",
        border: "var(--components-badge-success-border)",
        "closexitem-fg": "var(--components-badge-success-closexitem-fg)",
        "closexitem-fg-hover": "var(--components-badge-success-closexitem-fg_hover)",
      },
    },
    textbutton: {
      "primary-fg": "var(--components-textbutton-primary-fg)",
      "primary-fg-hover": "var(--components-textbutton-primary-fg_hover)",
      "secondary-fg": "var(--components-textbutton-secondary-fg)",
      "secondary-fg-hover": "var(--components-textbutton-secondary-fg_hover)",
    },
    buttons: {
      "button-primary": {
        bg: "var(--components-buttons-button-primary-bg)",
        "bg-hover": "var(--components-buttons-button-primary-bg_hover)",
        fg: "var(--components-buttons-button-primary-fg)",
      },
      "destructive-primary": {
        bg: "var(--components-buttons-destructive-primary-bg)",
        "bg-hover": "var(--components-buttons-destructive-primary-bg_hover)",
        fg: "var(--components-buttons-destructive-primary-fg)",
      },
      "button-secondary": {
        bg: "var(--components-buttons-button-secondary-bg)",
        "bg-hover": "var(--components-buttons-button-secondary-bg_hover)",
        fg: "var(--components-buttons-button-secondary-fg)",
        "fg-hover": "var(--components-buttons-button-secondary-fg_hover)",
        border: "var(--components-buttons-button-secondary-border)",
      },
      "destructive-secondary": {
        bg: "var(--components-buttons-destructive-secondary-bg)",
        "bg-hover": "var(--components-buttons-destructive-secondary-bg_hover)",
        fg: "var(--components-buttons-destructive-secondary-fg)",
        "fg-hover": "var(--components-buttons-destructive-secondary-fg_hover)",
        border: "var(--components-buttons-destructive-secondary-border)",
      },
      "button-tertiary": {
        bg: "var(--components-buttons-button-tertiary-bg)",
        "bg-hover": "var(--components-buttons-button-tertiary-bg_hover)",
        fg: "var(--components-buttons-button-tertiary-fg)",
        "fg-hover": "var(--components-buttons-button-tertiary-fg_hover)",
      },
      "destructive-tertiary": {
        bg: "var(--components-buttons-destructive-tertiary-bg)",
        "bg-hover": "var(--components-buttons-destructive-tertiary-bg_hover)",
        fg: "var(--components-buttons-destructive-tertiary-fg)",
        "fg-hover": "var(--components-buttons-destructive-tertiary-fg_hover)",
      },
    },
    accordion: {
      "open-bg": "var(--components-accordion-open-bg)",
      "open-bg-hover": "var(--components-accordion-open-bg_hover)",
      "open-border": "var(--components-accordion-open-border)",
    },
    tooltip: {
      typo: "var(--components-tooltip-typo)",
    },
    "switch-pill": {
      disabled: "var(--components-switch-pill-disabled)",
    },
    card: {
      "border-1": "var(--components-card-border_1)",
      "border-2": "var(--components-card-border_2)",
    },
    avatar: {
      bg: "var(--components-avatar-bg)",
      typo: "var(--components-avatar-typo)",
      border: "var(--components-avatar-border)",
      "contrast-border": "var(--components-avatar-contrast-border)",
      "avatargroup-separator-border": "var(--components-avatar-avatargroup-separator-border)",
    },
  },
} as const;
