export const GRADIENTS = {
  horizontal_1: "gradient-1-horizontal",
  vertical_1: "gradient-1-vertical",
  angular_1: "gradient-1-angular",
  horizontal_2: "gradient-2-horizontal",
  horizontal_3: "gradient-3-horizontal",
  angular_3: "gradient-3-angular",
  component_card_bg_gradient_1: "component-card-bg-gradient-1",
  gradient_glass_neon_45: "gradient-glass-neon-45",
  gradient_glass_neon_80: "gradient-glass-neon-80",
  cosmic_night: "gradient-cosmic-night",
  deep_ocean: "gradient-deep-ocean",
  velvet_dusk: "gradient-velvet-dusk",
  arctic_abyss: "gradient-arctic-abyss",
  ember_shadow: "gradient-ember-shadow",
  mystic_twilight: "gradient-mystic-twilight",
} as const;
